"""Render workflows JSON ({stem: workflow}) to <out>/<stem>.yaml."""

import json
import sys
from pathlib import Path

import yaml

HEADER = """# Generated by flake-ci (ci.github). Do not edit manually.
# Regenerate with:
#   nix run .#write-files
"""


def represent_str(dumper, data):
    lines = [line.rstrip() for line in data.splitlines()]
    text = "\n".join(lines)
    style = "|" if len(lines) > 1 else None
    return dumper.represent_scalar("tag:yaml.org,2002:str", text, style=style)


yaml.add_representer(str, represent_str)

workflows = json.loads(Path(sys.argv[1]).read_text())
out = Path(sys.argv[2])
out.mkdir()
for stem, workflow in workflows.items():
    (out / f"{stem}.yaml").write_text(HEADER + yaml.dump(workflow))
