{
  commits,
  lib,
  pkgs,
  repository,
}: let
  owner = builtins.head (lib.splitString "/" repository);
  settings = (pkgs.formats.toml {}).generate "cog-settings.toml" {
    from_latest_tag = true;
    ignore_merge_commits = true;
    ignore_fixup_commits = true;
    tag_prefix = "v";
    pre = "rc.*";

    commit_types =
      lib.mapAttrs (
        _: type:
          {changelog_title = type.title;}
          // (
            if type.bump == null
            then {omit_from_changelog = true;}
            else {"bump_${type.bump}" = true;}
          )
      )
      commits.types;

    changelog = {
      path = "CHANGELOG.md";
      template = "remote";
      remote = "github.com";
      inherit owner;
      repository = lib.removePrefix "${owner}/" repository;
    };
  };
in
  pkgs.runCommandLocal "cog.toml" {} ''
    {
      printf '%s\n' \
        '# Generated by flake-ci (ci.commits, ci.release). Do not edit manually.' \
        '# Regenerate with: nix run .#write-files' \
        ""
      cat ${settings}
    } > "$out"
  ''
